import { useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom"; 

function Signup() {
  const [email, setEmail] = useState("");
    const [username, setUsername] = useState("");
      const [password, setPassword] = useState("");
        const navigate = useNavigate(); 

          const handleSignup = async (e) => {
              e.preventDefault();
                  try {
                        // إرسال بيانات التسجيل للسيرفر
                              await axios.post("/api/auth/register", { 
                                      email: email,
                                              username: username,
                                                      password: password 
                                                            });
                                                                  
                                                                        alert("Account Created Successfully! Please Log in.");
                                                                              navigate("/"); // بعد النجاح، نعود لصفحة الدخول

                                                                                  } catch (err) {
                                                                                        alert(err.response?.data?.message || "Error creating account");
                                                                                            }
                                                                                              };

                                                                                                const styles = {
                                                                                                    container: {
                                                                                                          display: "flex",
                                                                                                                flexDirection: "column",
                                                                                                                      alignItems: "center",
                                                                                                                            justifyContent: "center",
                                                                                                                                  minHeight: "100vh",
                                                                                                                                        backgroundColor: "white",
                                                                                                                                              padding: "20px",
                                                                                                                                                    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
                                                                                                                                                        },
                                                                                                                                                            wrapper: {
                                                                                                                                                                  width: "100%",
                                                                                                                                                                        maxWidth: "350px",
                                                                                                                                                                              display: "flex",
                                                                                                                                                                                    flexDirection: "column",
                                                                                                                                                                                          alignItems: "center",
                                                                                                                                                                                                textAlign: "center",
                                                                                                                                                                                                    },
                                                                                                                                                                                                        logo: {
                                                                                                                                                                                                              fontSize: "3.5rem",
                                                                                                                                                                                                                    fontWeight: "800",
                                                                                                                                                                                                                          color: "#0066ff",
                                                                                                                                                                                                                                marginBottom: "10px",
                                                                                                                                                                                                                                      letterSpacing: "-1px",
                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                              subtitle: {
                                                                                                                                                                                                                                                    color: "#8e8e8e",
                                                                                                                                                                                                                                                          fontSize: "16px",
                                                                                                                                                                                                                                                                fontWeight: "600",
                                                                                                                                                                                                                                                                      marginBottom: "30px",
                                                                                                                                                                                                                                                                            lineHeight: "20px",
                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                    form: {
                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                display: "flex",
                                                                                                                                                                                                                                                                                                      flexDirection: "column",
                                                                                                                                                                                                                                                                                                            gap: "12px",
                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                    input: {
                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                padding: "14px",
                                                                                                                                                                                                                                                                                                                                      border: "1px solid #dbdbdb",
                                                                                                                                                                                                                                                                                                                                            backgroundColor: "#fafafa",
                                                                                                                                                                                                                                                                                                                                                  borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                        fontSize: "14px",
                                                                                                                                                                                                                                                                                                                                                              outline: "none",
                                                                                                                                                                                                                                                                                                                                                                    boxSizing: "border-box", 
                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                            signupButton: {
                                                                                                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: "#0066ff",
                                                                                                                                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                          border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "50px",
                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                loginLink: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginTop: "25px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: "#00376b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={styles.container}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={styles.wrapper}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1 style={styles.logo}>Nexo</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={styles.subtitle}>Sign up to see photos and videos from your friends.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <form onSubmit={handleSignup} style={styles.form}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="email" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Email" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="text" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Username" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={username}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="password" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Password" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" style={styles.signupButton}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Sign up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={styles.loginLink} onClick={() => navigate("/")}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Have an account? <b>Log in</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default Signup;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            